### ISSUE TITLE
API Scope error

### ISSUE THREAD

**Issue by 7flash** [ezzcodeezzlife/dalle-node#13]
![image](https://user-images.githubusercontent.com/4569866/182305539-b3945d06-4631-4637-b161-fc57a1cc50bf.png)

**Comment by 7flash** [comment]
https://github.com/1998code/DALLE-2-App/issues/12

**Comment by 7flash** [comment]
nvm it worked when I regenerated token as per instruction.. it seems OpenAI rotating tokens and that requires to refresh them periodically..

**Comment by ezzcodeezzlife** [comment]
yea. maybe there is a way to do this programmatically 🤔 @7flash

**Comment by jtsalten** [comment]
I'm getting that same error... 
{
  "error": {
    "message": "Your key is missing a required scope: app.labs",
    "type": "invalid_request_error",
    "param": null,
    "code": "missing_scope"
  }
}

I'm regenerating the API-KEY each time... do I need any special permission/privilege to access dalle2 or they've just restricted access to everybody?

**Comment by ezzcodeezzlife** [comment]
> nvm it worked when I regenerated token as per instruction.. it seems OpenAI rotating tokens and that requires to refresh them periodically..

its not the api key you need to get your bearer token @jtsalten

**Comment by jtsalten** [comment]
Thanks.So... how can I get the bearer token? I was trying just to follow the setup instructions, I have the OpenAI account... but when I open https://labs.openai.com I can't see the "Network Tab in Developer Tools" ... so I cannot get that token... If I try to go directly to https://labs.openai.com/api/labs/tasks it asks me for a username/password... which it doesn't seem to be the ones from my account... In fact, when the login fails, it tells me that I need an API Key from beta.openai.com... 
{
  "error": {
    "message": "You didn't provide an API key. You need to provide your API key in an Authorization header using Bearer auth (i.e. Authorization: Bearer YOUR_KEY), or as the password field (with blank username) if you're accesing the API from your browser and are prompted for a username and password. You can obtain an API key from https://beta.openai.com.",
    "type": "invalid_request_error",
    "param": null,
    "code": null
  }
}


I'm in a loop. :-( What am I doing wrong? 
thanks in advance,    En martes, 11 de octubre de 2022, 09:50:07 CEST, fabi.s ***@***.***> escribió:  
 
 



nvm it worked when I regenerated token as per instruction.. it seems OpenAI rotating tokens and that requires to refresh them periodically..


its not the api key you need to get your bearer token

**Comment by ezzcodeezzlife** [comment]
Developer Tools (F12 on windows -> then there is the network tab in there) @jtsalten

**Comment by jtsalten** [comment]
Hi again,forget it... I think I got it. The bearer token It's in the page request itself!... I wasn't considering it was kind of a hack.
thanks!

    En martes, 11 de octubre de 2022, 17:05:20 CEST, José Tomás Salvador ***@***.***> escribió:  
 
  Thanks.So... how can I get the bearer token? I was trying just to follow the setup instructions, I have the OpenAI account... but when I open https://labs.openai.com I can't see the "Network Tab in Developer Tools" ... so I cannot get that token... If I try to go directly to https://labs.openai.com/api/labs/tasks it asks me for a username/password... which it doesn't seem to be the ones from my account... In fact, when the login fails, it tells me that I need an API Key from beta.openai.com... 
{
  "error": {
    "message": "You didn't provide an API key. You need to provide your API key in an Authorization header using Bearer auth (i.e. Authorization: Bearer YOUR_KEY), or as the password field (with blank username) if you're accesing the API from your browser and are prompted for a username and password. You can obtain an API key from https://beta.openai.com.",
    "type": "invalid_request_error",
    "param": null,
    "code": null
  }
}


I'm in a loop. :-( What am I doing wrong? 
thanks in advance,    En martes, 11 de octubre de 2022, 09:50:07 CEST, fabi.s ***@***.***> escribió:  
 
 



nvm it worked when I regenerated token as per instruction.. it seems OpenAI rotating tokens and that requires to refresh them periodically..


its not the api key you need to get your bearer token

**Comment by jtsalten** [comment]
Many thanks! 

Enviado desde Yahoo Mail con Android 
 
  El mar, oct 11, 2022 a 17:11, ***@***.***> escribió:   


Developer Tools (F12 on windows -> then there is the network tab in there) @jtsalten
