### ISSUE TITLE
Any idea how OpenAI deems a base64 image as invalid?

### ISSUE THREAD

**Issue by Andrewcpu** [ezzcodeezzlife/dalle-node#16]
It seems that when you submit a variation request it uses the following JSON body:
`{
    task_type: "variations",
    prompt: {
        batch_size: 3,
        image: "BASE64IMAGESTRING_HERE"
    }
}`

However, this yields a response that the image was invalid... Plugging the base64 data scraped from the official website into a base64 image decoder does yield the image, but plugging my own base64 in there yields an error... Any ideas as to why? Are they tagging the data somewhere in the base64?

**Comment by ezzcodeezzlife** [comment]
thisis another project but maybe it helps: [dalle2-in-python/pull/7](https://github.com/ezzcodeezzlife/dalle2-in-python/pull/7)
