### ISSUE TITLE
I'm not able to import his library in typescript firebase functions project 

### ISSUE THREAD

**Issue by Yahya-khodr** [ezzcodeezzlife/dalle-node#19]

**Comment by ezzcodeezzlife** [comment]
try add this line above your import of the module like:
```
// @ts-ignore 
import { Dalle } from "dalle-node"
```

**Comment by Yahya-khodr** [comment]
@ezzcodeezzlife Thank you.
But now it's preventing me from deploying my firebase function.
any suggestions how to tackle this issue ?
Thank you again

**Comment by Yahya-khodr** [comment]
@ezzcodeezzlife I think I figured out the problem that this dalle-node package REQUIRE_ESM I think we need it to support commonJs to use it in my project

**Comment by Yahya-khodr** [comment]
@ezzcodeezzlife I have tried to implement your library and make a call to https://labs.openai.com/api/labs/ in Postman and i added my API key in the header but it keeps saying wrong API key provided. 
How to fix that ?

**Comment by ezzcodeezzlife** [comment]
@Yahya-khodr make sure its your Bearer Key and not a GPT3 API Key. You can find how its done in the readme.  Also your request kind of has to match the request from the normal frontend.
