### ISSUE TITLE
Image Format

### ISSUE THREAD

**Issue by aswinpreman06** [ezzcodeezzlife/dalle-node#22]
Hi,
The image format in response is coming in WEBP format.Is there any way to get response in jpeg or png?

Thanks,
Aswin Preman

**Comment by 1998code** [comment]
@aswinpreman06 You can convert the image from webp to jpg/png using Sharp Library.
Here's an example app with the support of PNG, JPG, GIF, and AVIF:
https://github.com/1998code/DALLE-2-App
😄
