### ISSUE TITLE
Response is 'undefined'

### ISSUE THREAD

**Issue by Leekao** [ezzcodeezzlife/dalle-node#23]
When I try to use the library the response is always undefined even though the generations are available on the web.

**Comment by michelecerruto** [comment]
Me too, is there a way to fix?

**Comment by ezzcodeezzlife** [comment]
@michelecerruto i recommend using the new official dalle2 api openai just released 🚀

**Comment by michelecerruto** [comment]
@ezzcodeezzlife thank you! I'm already using it 🎉🤩
