### ISSUE TITLE
Add support to make image public and generate shareable link

### ISSUE THREAD

**Issue by ezzcodeezzlife** [ezzcodeezzlife/dalle-node#5]
The DALL·E UI allows you to designate an image as public and then creates a shareable link. It would be nice to be able to do this programatically.

**Comment by dillonstreator** [comment]
@ezzcodeezzlife where in the UI is this exposed?
Maybe it has been removed since July24. If it's still available, can you provide Video/Pictures of this functionality? I'd like to explore this.

**Comment by ezzcodeezzlife** [comment]
after generating an image there is a small share button on the top

**Comment by dillonstreator** [comment]
Ah I see it's just a post request to `/generations/{genId}/share`
