### ISSUE TITLE
Refactor request - Use a different library than "request"

### ISSUE THREAD

**Issue by Christopher-Hayes** [ezzcodeezzlife/dalle-node#8]
The `request` library [has been deprecated for years](https://www.npmjs.com/package/request).

A well-maintained library like [node-fetch](https://www.npmjs.com/package/node-fetch), [axios](https://www.npmjs.com/package/axios), or [got](https://www.npmjs.com/package/got) should be transitioned to.

**Comment by ezzcodeezzlife** [comment]
done 🔥🔥
